# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim AS uv

# Set the working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy pyproject.toml and uv.lock for dependencies
COPY pyproject.toml uv.lock ./

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Copy the entire source code into the container
COPY src/ ./src/

# Set the environment variable for Tiingo API Key
ENV TIINGO_API_KEY=your_api_key_here

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Default command to run the MCP server
CMD ["uv", "run", "mcp-trader"]
